services:
  - type: web
    name: trading-signals-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    plan: free
    envVars:
      - key: MONGO_URI
        sync: false

    - type: cron
    name: train-ai-model
    env: python
    schedule: "0 */12 * * *"  # Every 12 hours (or "0 0 * * 0" for weekly)
    buildCommand: pip install -r requirements.txt
    startCommand: python train_model.py
    envVars:
      - key: MONGO_URI
        sync: false
